const tray=document.querySelector("#eggTray"),nests=[...document.querySelectorAll(".nest")],feedback=document.querySelector("#feedback"),progress=document.querySelector("#progress"),meter=document.querySelector("#meterFill"),celebration=document.querySelector("#celebration");
let selected=null,sorted=0,drag=null;
const shuffle=a=>a.sort(()=>Math.random()-.5);
const roundNumbers=()=>shuffle([1,11,21].flatMap(start=>shuffle(Array.from({length:10},(_,i)=>start+i)).slice(0,4)));
const rangeFor=n=>n<=10?[1,10]:n<=20?[11,20]:[21,30];
function setSelected(egg){document.querySelectorAll(".egg.selected").forEach(el=>el.classList.remove("selected"));selected=egg;if(egg){egg.classList.add("selected");feedback.textContent="Egg "+egg.dataset.number+" selected. Now choose its nest."}}
function makeEgg(n){const egg=document.createElement("button");egg.type="button";egg.className="egg";egg.dataset.number=n;egg.textContent=n;egg.setAttribute("aria-label","Number "+n+" egg");egg.addEventListener("click",()=>setSelected(selected===egg?null:egg));egg.addEventListener("pointerdown",startDrag);return egg}
function newRound(){selected=null;sorted=0;tray.replaceChildren(...roundNumbers().map(makeEgg));nests.forEach(n=>{n.classList.remove("ready","wrong");n.querySelector(".nest-eggs").replaceChildren()});celebration.hidden=true;updateProgress();feedback.textContent="Choose an egg to begin."}
function updateProgress(){progress.innerHTML="<strong>"+sorted+"</strong> of 12 eggs sorted";meter.style.width=(sorted/12*100)+"%"}
function placeEgg(egg,nest){if(!egg||!nest)return;const number=+egg.dataset.number,min=+nest.dataset.min,max=+nest.dataset.max;if(number>=min&&number<=max){const mini=document.createElement("span");mini.className="mini-egg";mini.textContent=number;nest.querySelector(".nest-eggs").append(mini);egg.remove();selected=null;sorted++;updateProgress();feedback.textContent="Yes! "+number+" belongs in the "+min+"–"+max+" nest.";if(sorted===12)setTimeout(()=>{celebration.hidden=false;document.querySelector("#playAgain").focus()},450)}else{nest.classList.remove("wrong");void nest.offsetWidth;nest.classList.add("wrong");const [a,b]=rangeFor(number);feedback.textContent="Nearly! "+number+" belongs between "+a+" and "+b+". Try again.";setSelected(egg)}}
nests.forEach(nest=>nest.addEventListener("click",()=>{if(selected)placeEgg(selected,nest)}));
function startDrag(e){if(e.button!==0)return;const egg=e.currentTarget;drag={egg,id:e.pointerId,startX:e.clientX,startY:e.clientY,moved:false};egg.setPointerCapture(e.pointerId);egg.addEventListener("pointermove",moveDrag);egg.addEventListener("pointerup",endDrag);egg.addEventListener("pointercancel",endDrag)}
function moveDrag(e){if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.hypot(dx,dy)>6)drag.moved=true;if(drag.moved){drag.egg.classList.add("dragging");drag.egg.style.transform="translate("+dx+"px,"+dy+"px) scale(1.08)";drag.egg.style.pointerEvents="none";const under=document.elementFromPoint(e.clientX,e.clientY);drag.egg.style.pointerEvents="";nests.forEach(n=>n.classList.toggle("ready",n===under?.closest(".nest")))}}
function endDrag(e){if(!drag||e.pointerId!==drag.id)return;const {egg,moved}=drag;egg.style.pointerEvents="none";const under=document.elementFromPoint(e.clientX,e.clientY);egg.style.pointerEvents="";const nest=under?.closest(".nest");egg.releasePointerCapture(e.pointerId);egg.removeEventListener("pointermove",moveDrag);egg.removeEventListener("pointerup",endDrag);egg.removeEventListener("pointercancel",endDrag);egg.classList.remove("dragging");egg.style.transform="";nests.forEach(n=>n.classList.remove("ready"));drag=null;if(moved&&nest){e.preventDefault();placeEgg(egg,nest)}}
document.querySelector("#newRound").addEventListener("click",newRound);document.querySelector("#playAgain").addEventListener("click",newRound);celebration.addEventListener("click",e=>{if(e.target===celebration)newRound()});newRound();
